### PR TITLE
Implements data.europa.eu support

### PR DESCRIPTION
**Pull request by micafer**

### CODE REVIEW

**Comment by micafer** [comment]
Implements #86

**Comment by alvarolopez** [comment]
@J535D165 any chances this can be merged soon?

**Comment by J535D165** [comment]
Very cool. Will make a release soon (have to fix figshare and osf)

**Comment by J535D165** [comment]
The PR fails on the main branch. Let me check why.

**Comment by J535D165** [comment]
The file used for the check was replaced by a new file with a slightly different file name.

**Pull request merged**
